gradlex-org/extra-java-module-info

build.gradle.kts, src/functionalTest/groovy/de/jjohannes/gradle/javamodules/test/ExtraJavaModuleInfoTest.groovy, src/main/java/de/jjohannes/gradle/javamodules/ExtraModuleInfoTransform.java
An example of such a jar: https://repo1.maven.org/maven2/javax/inject/javax.inject/1/javax.inject-1.jar
P.S. I know that there's a properly modularized Jakarta EE replacement, but I believe the plugin should still support the subject and do not throw an NPE if it encounters a jar like that.
=> Fix handling jars without manifest

src/functionalTest/groovy/de/jjohannes/gradle/javamodules/test/ExtraJavaModuleInfoTest.groovy, src/main/java/de/jjohannes/gradle/javamodules/ExtraModuleInfoTransform.java, src/main/java/de/jjohannes/gradle/javamodules/ModuleInfo.java
These are two uses cases I ran into while trying to modularize a small Spring Boot project.
* `provides ... with`. If a JAR file has module-info.class, any SPI implementations declared in META-INF/services/* are not visible to `java.util.ServiceLoader`. Fortunately, this issue can be fixed by automatically translating this metadata into `module-info.class` `provides` entries.
* `requires static`. Spring Boot heavily exploits this concept of "optional dependencies" in `auto-configurations`. Later on, these optional dependencies are brought to the dependency graph by the `starter` libraries. The latter can be covered by `requires` whilst the former is not supported by the plugin.
Let me know if you'd like me to split this PR into two separate PRs or if you have any suggestions on how the …
=> Add support for provides with/requires static declarations

src/main/java/de/jjohannes/gradle/javamodules/ExtraModuleInfoTransform.java
When transforming a signed jar we need to make sure the signature is removed when the manifest is modified.
Otherwise we can get errors like this:
```
> Task :my-application:run FAILED
Error occurred during initialization of boot layer
java.lang.module.FindException: Unable to derive module descriptor for ...\.gradle\caches\transforms-3\...\transformed\org.eclipse.paho.client.mqttv3-1.2.5-module.jar
Caused by: java.lang.SecurityException: Invalid signature file digest for Manifest main attributes
```
It might be rare to find a signed jar (without an existing module-info or automatic module name) so here is an example to test with:
```
extraJavaModuleInfo {
automaticModule("org.eclipse.paho.client.mqttv3-1.2.5.jar", "org.eclipse.paho.client.mqttv3")
}
dependencies { …
```
=> Exlude signatures from signed jars

src/main/java/de/jjohannes/gradle/javamodules/ExtraModuleInfoPlugin.java, src/test/groovy/de/jjohannes/gradle/javamodules/test/ConfigurationDetailsFunctionalTest.groovy, src/test/groovy/de/jjohannes/gradle/javamodules/test/fixture/LegacyLibraries.groovy
329293473e9bd22417176f2c68293b66608a3e38 added support for the convenient 'group:name' notation instead of the file name. This commit extends this functionality to also work for dependencies that are not in the runtime classpath (i.e. statically required modules).
=> Support 'group:name' notation for compile-only dependencies

src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/main/java/org/gradlex/javamodule/moduleinfo/ModuleInfo.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/AbstractFunctionalTest.groovy
Based on a real world example that uses the jcache api. In this case the application would not start because the generated module-info.java was missing a `uses` clause, which could not be added to the generated module-info using the plugin.
This change adds support for uses directives and adds a unit test to verify that the resulting module-info is correct.
=>  Added support for 'uses' directives in generated the module-info.java

README.md, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPlugin.java, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPluginExtension.java, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/main/java/org/gradlex/javamodule/moduleinfo/ModuleDescriptorRecommendation.java, src/main/java/org/gradlex/javamodule/moduleinfo/ModuleInfo.java, src/main/java/org/gradlex/javamodule/moduleinfo/tasks/ModuleDescriptorRecommendation.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/AllowAutomaticModulesFunctionalTest.groovy, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/RealModuleJarPatchingFunctionalTest.groovy, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/RecommendModuleSpecFunctionalTest.groovy, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/RequireAllDefinedDependenciesFunctionalTest.groovy, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/fixture/GradleBuild.groovy
Hi @jjohannes . I apologize in advance if this is a too big of a PR. I'm happy to split it into a few smaller ones; however, each commit represents a different piece of functionality so it should be easy to review/merge only portions of it.
This PR add the three new features to the plugin. 
This is useful when dealing with big (10+ elements) classpath's with the goal to migrate 100% of them to be real modules. Similar to `failOnMissingModuleInfo`, this setting will fail the build if a configuration contains a JAR with an automatic module defined via the JAR Manifest.
Even modular JARs may carry invalid module descriptors. For example, `org.apache.tomcat.embed:tomcat-embed-core:10.1.13` `exports` a package that does not exist (`org.apache.catalina.ssi`) in the JAR and as a result, this …
=> Enhancements: failOnAutomaticModules, Real Module Patching, and Module Specs Generation

src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/main/java/org/gradlex/javamodule/moduleinfo/ModuleSpec.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/EdgeCasesFunctionalTest.groovy
=> Add check that  existing 'Automatic-Module-Names' are not changed accidentally

README.md, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/main/java/org/gradlex/javamodule/moduleinfo/ModuleInfo.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/ExportsFunctionalTest.groovy, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/OpensFunctionalTest.groovy
This PR addressed the gap we currently have.
=> Allow granular `exports` and `opens` declarations

src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPlugin.java, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/main/java/org/gradlex/javamodule/moduleinfo/PublishedMetadata.java
Before the 'transitive' scope was not correct (see removed comment in code). This let to different results depending for components that were direct and transitive dependencies.
Follow up to #81
=> 'requireAllDefinedDependencies' computes correct scopes

src/main/java/org/gradlex/javamodule/moduleinfo/FilePathToModuleCoordinates.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/FilePathToModuleCoordinatesTest.groovy
=> Relax Jar path matching for coordinates extraction

CHANGELOG.md, README.md, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPlugin.java, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPluginExtension.java, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/main/java/org/gradlex/javamodule/moduleinfo/IdValidator.java, src/main/java/org/gradlex/javamodule/moduleinfo/PublishedMetadata.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/RequireAllDefinedDependenciesFunctionalTest.groovy, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/fixture/GradleBuild.groovy
This way, a build setup can be created with a Configuration available in ALL projects that resolves to the same version of every module used. Then the metadata input to the transform, to process 'requireAllDefinedDependencies', is the same for a certain Jar independent of the classpath it is used on.
Resolve #137
=> Add configuration option for 'versionsProvidingConfiguration'

src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java
A small optimization motivated by this comment: https://github.com/gradlex-org/extra-java-module-info/issues/134#issuecomment-2614151253
=> Return early if a Jar is not modified and all checks are disabled

CHANGELOG.md, README.md, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/main/java/org/gradlex/javamodule/moduleinfo/ModuleInfo.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/AbstractFunctionalTest.groovy, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/EdgeCasesFunctionalTest.groovy, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/RealModuleJarPatchingFunctionalTest.groovy
=> Add preserveExisting option to patch real modules

CHANGELOG.md, README.md, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/main/java/org/gradlex/javamodule/moduleinfo/ModuleSpec.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/RemovePackageFunctionalTest.groovy
=> Add removePackage option

CHANGELOG.md, README.md, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPlugin.java, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPluginExtension.java, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/LocalJarTransformFunctionalTest.groovy, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/fixture/GradleBuild.groovy
=> Add skipLocalJars option and error message when used at configuration time

CHANGELOG.md, README.md, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPlugin.java, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPluginExtension.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/PluginActivationFunctionalTest.groovy
=> Add 'disable(...)' and 'enable(...)' options

CHANGELOG.md, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/main/java/org/gradlex/javamodule/moduleinfo/ModuleInfo.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/AbstractFunctionalTest.groovy
=> Add 'requiresStaticTransitive(...)' to module patch DSL

README.md, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/main/java/org/gradlex/javamodule/moduleinfo/ModuleInfo.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/IgnoreServiceProviderFunctionalTest.groovy
=> Allow ignoring specific service provider implementations

README.md
I was triggered by a space too much. I removed it.
I also added syntax highlighting of the example code.
=> Add syntax highlighting (and remove obsolete space)

CHANGELOG.md, README.md, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPlugin.java, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoPluginExtension.java, src/main/java/org/gradlex/javamodule/moduleinfo/ExtraJavaModuleInfoTransform.java, src/test/groovy/org/gradlex/javamodule/moduleinfo/test/ForbidDerivedModuleNameChangeFunctionalTest.groovy
This option is for library developers to make sure they do not use modified names of Jars without `module-info` and without `Automatic-Module-Name`.
Motivated by this discussion: https://github.com/APIdia-net/apidia.net/issues/2#issuecomment-3048606639
TODO:
=> Add 'failOnModifiedDerivedModuleNames' option
